added categories page
VitaliyBogdanuk/bro-app-client pull request #5
Opened 2023-11-16 21:14 UTC by OlegShcherbak

added categories page

2023-11-16 21:39 UTC, VitaliyBogdanuk requested changes

2023-11-16 21:39 UTC, VitaliyBogdanuk commented on pages/categories.vue
> +// import axios from '@nuxtjs/axios'
?

2023-11-16 21:39 UTC, VitaliyBogdanuk commented on styles.css
> +color:var(--text_colo_w);
щось тут з назвою змінної

2023-11-21 18:33 UTC, OlegShcherbak commented on styles.css
> +color:var(--text_colo_w);
fixed

2023-11-21 18:33 UTC, OlegShcherbak commented on pages/categories.vue
> +// import axios from '@nuxtjs/axios'
clear)

2023-11-21 18:36 UTC, merged